name: 'angona_kalitao'
version: '1.0.0'

profile: 'angona_kalitao'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  angona_kalitao:
    fact:
      +schema: fact
      +materialized: table
    dim:
      +schema: dim
      +materialized: table
    staging:
      +schema: marts
      +materialized: view
